---
# =====================================================================
# inventory/group_vars/stage/system.yml
#
# Purpose:
#   System localization and environment for stage.
# =====================================================================

# ---------------------------------------------------------------------
# Environment Configuration:
# ---------------------------------------------------------------------
env: "stage"
