---
# =====================================================================
# roles/scenarios/server/tasks/redhat.yml
# =====================================================================

- ansible.builtin.include_tasks: "default.yml"
