---
# roles/container/container_loader/tasks/main.yml
- name: Determine dynamic container backend
  ansible.builtin.set_fact:
    ls_container_backend: "{{ 'podman' if ('restricted' in node_tags) else 'docker' }}"

- name: Execute Docker Backend
  community.docker.docker_container:
    name: "{{ app_name }}"
    image: "{{ app_image | default(app_name ~ ':' ~ (app_version | default('latest'))) }}"
    state: started
    restart_policy: always
    ports: "{{ app_ports | default([]) }}"
    volumes: "{{ app_volumes | default([]) }}"
  when: ls_container_backend == 'docker'

- name: Execute Podman Backend
  containers.podman.podman_container:
    name: "{{ app_name }}"
    image: "{{ app_image | default(app_name ~ ':' ~ (app_version | default('latest'))) }}"
    state: started
    ports: "{{ app_ports | default([]) }}"
    volumes: "{{ app_volumes | default([]) }}"
  when: ls_container_backend == 'podman'
