# docker-compose.yml

services:
  alpine:
    image: alpine:3.23.3
    container_name: uls_alpine
    command: tail -f /dev/null
    networks:
      - uls_net

  debian:
    image: debian:13.3-slim
    container_name: uls_debian
    command: tail -f /dev/null
    networks:
      - uls_net

  rhel:
    image: rockylinux/rockylinux:10.1
    container_name: uls_rhel
    command: tail -f /dev/null
    networks:
      - uls_net

networks:
  uls_net:
    driver: bridge
