---
# =====================================================================
# roles/init/tasks/kubeadm/almalinux.yml
#
# Purpose:
#   Install Kubeadm on AlmaLinux (delegates to redhat.yml).
# =====================================================================

- ansible.builtin.import_tasks: "redhat.yml"
