---
# =====================================================================
# roles/init/tasks/kubeadm/default.yml
# =====================================================================
- name: "Skip Kubeadm on unsupported OS"
  ansible.builtin.debug:
    msg: "Kubeadm setup is not yet specialized for this OS."
  when: os_family not in ['debian', 'redhat', 'alpine', 'suse', 'darwin']
