---
# =====================================================================
# roles/scenarios/desktop/vars/redhat.yml
# =====================================================================

desktop_apps_overrides:
  app_packages:
    - "vim"
