all:
  hosts:
    localhost:
      ansible_connection: ssh
      ansible_host: 127.0.0.1
      node_tags:
        - host
        - docker_host
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=accept-new
      -o UserKnownHostsFile=/dev/null
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
