# =====================================================================
# inventory/group_vars/prod/system.yml
#
# Purpose:
#   System localization and environment for prod.
# =====================================================================

# ---------------------------------------------------------------------
# Environment Configuration:
# ---------------------------------------------------------------------
env: "prod"
