---
# =====================================================================
# roles/apps/tasks/vscode_server/native/debian.yml
# =====================================================================

- name: "Vscode_server (Debian): Include Linux implementation"
  ansible.builtin.include_tasks: "linux.yml"
