---
# =====================================================================
# roles/apps/tasks/vscode_server/native/redhat.yml
# =====================================================================

- name: "Vscode_server (RedHat): Include Linux implementation"
  ansible.builtin.include_tasks: "linux.yml"
