---
# =====================================================================
# roles/scenarios/develop/vars/alpine.yml
# =====================================================================

develop_apps_overrides:
  app_packages: []
