---
# =====================================================================
# roles/scenarios/develop/vars/darwin.yml
# =====================================================================

develop_apps_overrides:
  app_packages:
    - "vscode"
    - "antigravity"
    - "antigravity_tools"
    - "cc_switch"
    - "proxifier"
  # - "windterm"
  # - "wechat"
