---
# =====================================================================
# roles/scenarios/develop/vars/redhat.yml
# =====================================================================

develop_apps_overrides:
  app_packages:
    - "vscode"
    - "antigravity"
    - "antigravity_tools"
    - "cc_switch"
    # - "windterm"
    # - "wechat"
    - "vscode_server"
