---
# =====================================================================
# roles/apps/vars/nginx/native/archlinux.yml
# =====================================================================

nginx_overrides:
  app_packages: ["nginx"]
  app_service: "nginx"
  # WHY: Arch Linux uses systemd for service management
  app_init_system: "systemd"
