---
# =====================================================================
# roles/apps/vars/nginx/native/redhat.yml
# =====================================================================

nginx_overrides:
  app_packages: ["nginx"]
  app_service: "nginx"
  # WHY: RHEL-family uses systemd for service management
  app_init_system: "systemd"
