---
# =====================================================================
# roles/apps/tasks/wechat/native/redhat.yml
# =====================================================================

# Wrapper to load generic linux install
- ansible.builtin.include_tasks: linux.yml
