---
# =====================================================================
# roles/native/vars/main.yml
#
# Purpose:
#   Infrastructure logic managed by snowdreamtech.
#
# =====================================================================
