---
# =====================================================================
# roles/init/tasks/kubespray/fedora.yml
#
# Purpose:
#   Setup Kubespray Controller on Fedora (delegates to redhat.yml).
# =====================================================================

- ansible.builtin.import_tasks: "redhat.yml"
