---
# =====================================================================
# roles/scenarios/deploy/tasks/alpine.yml
# =====================================================================

- ansible.builtin.include_tasks: "default.yml"
