---
# =====================================================================
# roles/scenarios/deploy/tasks/darwin.yml
# =====================================================================

- ansible.builtin.include_tasks: "default.yml"
