---
# =====================================================================
# roles/apps/vars/pnpm/native/darwin.yml
# =====================================================================

pnpm_overrides:
  app_packages: ["pnpm"]
  app_install_cmd: "" # Use package manager
