---
# =====================================================================
# roles/apps/vars/pnpm/native/redhat.yml
# =====================================================================

pnpm_overrides:
  # WHY: pnpm is installed via official install script on Alpine
  app_install_cmd: "curl -fsSL {{ github_proxy }}https://get.pnpm.io/install.sh | sh -"
  app_install_creates: "{{ ansible_user_home }}/.local/share/pnpm/pnpm"
