---
# =====================================================================
# roles/scenarios/deploy/vars/alpine.yml
# =====================================================================

deploy_apps_overrides:
  app_packages: []
