---
# =====================================================================
# roles/scenarios/deploy/vars/darwin.yml
# =====================================================================

deploy_apps_overrides:
  app_packages: []
