---
# =====================================================================
# roles/scenarios/deploy/vars/redhat.yml
# =====================================================================

deploy_apps_overrides:
  app_packages:
    - "vscode_server"
