---
# =====================================================================
# roles/apps/vars/redis/native/opensuse.yml
# =====================================================================

redis_overrides:
  app_packages: ["redis"]
  app_service: "redis"
  # WHY: openSUSE uses systemd for service management
  app_init_system: "systemd"
