# =====================================================================
# inventory/group_vars/dev/system.yml
#
# Purpose:
#   System localization and environment for dev.
# =====================================================================

# ---------------------------------------------------------------------
# Environment Configuration:
# ---------------------------------------------------------------------
env: "dev"
