---
# =====================================================================
# roles/apps/tasks/vscode/native/default.yml
# =====================================================================

- name: "vscode (Linux/Native): Fail on unsupported distribution {{ '(' ~ os_fingerprint ~ ')' if os_fingerprint is defined else '' }}"
  ansible.builtin.fail:
    msg: "Error: Distribution {{ os_distribution }} is not explicitly supported for native package installation. Please use Debian or RHEL based systems for full support."
