---
# =====================================================================
# roles/init/tasks/podman/fedora.yml
#
# Purpose:
#   Install Podman on Fedora (delegates to redhat.yml).
# =====================================================================

- ansible.builtin.import_tasks: "redhat.yml"
