---
# =====================================================================
# roles/init/tasks/k3s/centos.yml
#
# Purpose:
#   Install K3s on CentOS (delegates to redhat.yml).
# =====================================================================

- ansible.builtin.import_tasks: "redhat.yml"
