---
# =====================================================================
# roles/init/tasks/k3s/default.yml
# =====================================================================
- name: "Skip K3s on unsupported OS"
  ansible.builtin.debug:
    msg: "K3s setup is not yet specialized for this OS."
  when: os_family not in ['debian', 'redhat', 'alpine', 'suse', 'darwin']
