---
galaxy_info:
  author: "snowdreamtech"
  description: "Uniloader scenario: helloworld"
  company: "snowdreamtech"
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: "EL"
      versions: ["8", "9"]
    - name: "Debian"
      versions: ["bullseye", "bookworm"]
    - name: "Ubuntu"
      versions: ["focal", "jammy", "noble"]
    - name: "Alpine"
      versions: ["all"]
  galaxy_tags:
    - "scenario"
    - "helloworld"

dependencies: []
