---
# =====================================================================
# playbooks/test/test.yml
#
# Purpose:
#   Integration test playbook for verifying core functionalities.
#   Executes a full lifecycle test including:
#     - OS Bootstrapping.
#     - Native application deployment (HelloWorld).
#     - Container application deployment (Official and Snowdreamtech).
#
# Simple Usage:
#   ansible-playbook playbooks/test/test.yml
#
# Comprehensive Usage:
#   ansible-playbook -i inventory/test.yml playbooks/test/test.yml -vv
#
# =====================================================================

- name: "Run system-wide integration tests"
  hosts: all
  gather_facts: false

  # ---------------------------------------------------------------------
  # Test Pipeline: Deploy native and container apps.
  # ---------------------------------------------------------------------
  roles:
    # 0. Test
    - role: "test"
      # You can also dynamically override variables here, for example:
      # vars:
      #   project_name: "test"

    # 1. Setup fundamental environment.
    - role: "bootstrap"
    # vars:
    #   force: true

    # 2. Setup fundamental environment.
    - role: "context"

    # # 3. Setup fundamental environment.
    # - role: "init"

    # # 4. Setup fundamental environment.
    # - role: "base"

    # # 2. Deploy Native App Test.
    # - role: "apps/native/helloworld"

    # # 3. Deploy Container App Tests.
    # - role: "apps/container/official/helloworld"
