---
# =====================================================================
# roles/scenarios/desktop/tasks/darwin.yml
# =====================================================================

- ansible.builtin.include_tasks: "default.yml"
