---
# =====================================================================
# roles/scenarios/desktop/tasks/debian.yml
# =====================================================================

- ansible.builtin.include_tasks: "default.yml"
