---
# noqa
# roles/native/tasks/package_loader/mgmt_coursier.yml
#
# Purpose:
#   Modular task for Coursier (cs) package management.
#   - Focuses on "Strong Binary" installation/uninstallation.
# =====================================================================

- name: "Package (Coursier): Assert environment presence"
  ansible.builtin.assert:
    that: is_cs_installed
    fail_msg: "Coursier (cs) is required for this action but was not found."

- name: "Package (Coursier): Install requested packages"
  ansible.builtin.shell: "PATH={{ os_paths }} cs install {{ item }}"
  loop: "{{ pkg_cs_list }}"
  register: _cs_install_res
  changed_when: "'already installed' not in _cs_install_res.stdout"
  when: pkg_cs_list | length > 0
  become: false # Usually installs to platform-specific user bin
