---
# =====================================================================
# roles/scenarios/server/vars/alpine.yml
# =====================================================================

server_apps_overrides:
  app_packages:
    - "vim"
